# Generated by Django 5.1 on 2024-08-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_client_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client_count',
        ),
        migrations.AddField(
            model_name='room',
            name='client_count',
            field=models.IntegerField(default=0),
        ),
    ]
